### ISSUE TITLE
Screen reader reads aloud nested section tags

### ISSUE THREAD

**Issue by bobbysebolao** [FAC-Sixteen/BBFS#21]
If you click on any part of the team section, the chromevox screen reader reads out the names of all five of the ancestor `<section>` tags in which the content is nested. Perhaps one quick fix for this might be to change all but one of the `<section>` tags to `<div>` tags - maybe this would fix it because divs have no semantic meaning, so maybe the screen reader won't read them aloud?

**Comment by sylv1ah** [comment]
thanks Bobby problem resolved! 😄
